database:
  host: postgres
  port: 5432
  database: theme_evolution
  user: postgres
  password: postgres

ollama:
  base_url: http://ollama:11434
  generation_model: llama3.1
  embedding_model: nomic-embed-text
  generation_timeout: 120
  embedding_timeout: 30

thresholds:
  similarity_existing_theme: 0.75
  similarity_update_candidate: 0.50
  similarity_merge_themes: 0.85
  theme_split_variance: 0.40
  embedding_shift_recompute: 0.15
  keyword_contribution: 0.05
  min_responses_per_theme: 2

processing:
  batch_size: 100
  max_keywords_per_response: 10
  theme_update_drift_threshold: 0.20

ngrams:
  use_unigrams: true
  use_bigrams: true
  use_trigrams: true
  min_word_length: 3
  max_stopwords_in_phrase: 1
