services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: theme_evolution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db-init:
    image: postgres:16
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: theme_evolution
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./scripts/init_database.sh:/scripts/init_database.sh
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    command: ["/scripts/init_database.sh"]
    restart: "no"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "pgrep", "ollama"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama:11434
    volumes:
      - ./scripts/init_ollama.sh:/scripts/init_ollama.sh
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    command: ["/bin/sh", "/scripts/init_ollama.sh"]
    restart: "no"


  streamlit:
    build: .
    depends_on:
      db-init:
        condition: service_completed_successfully
      ollama-init:
        condition: service_completed_successfully
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=theme_evolution
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    command: streamlit run src/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
