[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
address = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "#667eea"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[ui]
hideTopBar = false
hideSidebarNav = true

